# Generated by Django 4.2.9 on 2024-09-19 09:52

from django.db import migrations, models
import site_info.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=site_info.utils.upload_logo_path, verbose_name='لوگو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='کلمات کلیدی متا')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='لینک فیس\u200cبوک')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='لینک توییتر')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='لینک یوتیوب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
                'ordering': ['-created_at'],
            },
        ),
    ]
