# Generated by Django 4.2.9 on 2024-09-19 09:56

from django.db import migrations, models
import django.db.models.deletion
import site_info.utils


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='phone',
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=site_info.utils.upload_logo_path, verbose_name='لوگو')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='site_info.siteinfo', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'لوگو',
                'verbose_name_plural': 'لوگوها',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('type', models.CharField(choices=[('mobile', 'موبایل'), ('landline', 'تلفن ثابت')], max_length=50, verbose_name='نوع تلفن')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='site_info.siteinfo', verbose_name='سایت')),
            ],
            options={
                'verbose_name': 'شماره تلفن',
                'verbose_name_plural': 'شماره تلفن\u200cها',
            },
        ),
    ]
