# Generated by Django 4.2.9 on 2024-09-19 10:45

from django.db import migrations, models
import site_info.utils


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0002_remove_siteinfo_logo_remove_siteinfo_phone_sitelogo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitelogo',
            name='site',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=site_info.utils.upload_logo_path, verbose_name='لوگو'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='SiteLogo',
        ),
    ]
