# Generated by Django 4.1.7 on 2024-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='آیا فروش باز است؟')),
            ],
            options={
                'verbose_name': 'کنترل فروش',
            },
        ),
    ]
