# Generated by Django 4.1.7 on 2024-09-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellControl',
        ),
    ]
