# Generated by Django 4.1.7 on 2023-12-13 09:13

import article.utils
import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('meta_title', models.TextField(help_text='حداکثر 60 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(60)], verbose_name='meta title (SEO)')),
                ('meta_description', models.TextField(help_text='حداکثر 160 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='meta description (SEO)')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('title', models.CharField(max_length=225, null=True, verbose_name='عنوان مقاله')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='محتوای مقاله')),
                ('thumbnail', models.ImageField(help_text='ابعاد عکس مربعی و حجم آن کمتر از 1 مگابایت باشد.', null=True, upload_to=article.utils.upload_thumbnail_path, verbose_name='تصویر شاخص')),
                ('publish', models.BooleanField(default=True, help_text='غیرفعال بودن این فیلد به معنی پیش نویس بودن مقاله و عدم انتشار آن در سایت می\u200cباشد.', verbose_name='در سایت منتشر شود')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=225, null=True, unique=True, verbose_name='پیوند یکتا')),
                ('reed_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدت زمان خواندن متن')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': '    مقالات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=128, null=True, verbose_name='عنوان')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='این فیلد را خالی بگذارید.', max_length=128, null=True, unique=True, verbose_name='پیوند یکتا')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': ' دسته بندی\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='article.article', verbose_name='مقاله مربوطه')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.category', verbose_name='دسته بندی'),
        ),
    ]
