# Generated by Django 4.1.7 on 2024-03-03 01:45

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author_category_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField(help_text='حداکثر 60 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(60)], verbose_name='meta title (SEO)')),
                ('meta_description', models.TextField(help_text='حداکثر 160 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='meta description (SEO)')),
                ('title', models.CharField(max_length=225, null=True, verbose_name='عنوان')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=225, null=True, unique=True, verbose_name='پیوند یکتا')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدیدها')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='article.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'هشتگ',
                'verbose_name_plural': 'هشتگ\u200cهای مقالات',
                'ordering': ('-views',),
            },
        ),
    ]
