# Generated by Django 4.1.7 on 2024-03-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articletag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ArticleTag', to='article.articletag', verbose_name='هشتگ\u200cها'),
        ),
    ]
