# Generated by Django 4.1.7 on 2023-12-13 09:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField(help_text='حداکثر 60 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(60)], verbose_name='meta title (SEO)')),
                ('meta_description', models.TextField(help_text='حداکثر 160 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='meta description (SEO)')),
            ],
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('subject', models.CharField(choices=[('phone_verify', 'تایید موبایل'), ('email_verify', 'تایید ایمیل'), ('birth_date', 'تبریک تولد'), ('other', 'سایر')], default='other', max_length=30, verbose_name='موضوع')),
                ('is_sent', models.BooleanField(default=True, verbose_name='وضعیت ارسال')),
                ('status_code', models.PositiveSmallIntegerField(null=True, verbose_name='کد وضعیت')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
