# Generated by Django 4.1.7 on 2024-02-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_email_contactmessage_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='phone',
            new_name='email',
        ),
    ]
