# Generated by Django 4.1.7 on 2024-02-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_phone_contactmessage_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'پیام ارتباط با ما', 'verbose_name_plural': 'پیام های ارتباط با ما'},
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ('-created_at',), 'verbose_name': 'تاریخچه sms', 'verbose_name_plural': 'تاریخچه sms ها'},
        ),
    ]
