# Generated by Django 4.1.7 on 2024-04-17 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_seo_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='subject',
            field=models.CharField(choices=[('phone_verify', 'تایید موبایل'), ('email_verify', 'تایید ایمیل'), ('birth_date', 'تبریک تولد'), ('new_order_customer', 'سفارش جدید (به مشتری)'), ('new_order_admin', 'سفارش جدید (به ادمین)'), ('other', 'سایر')], default='other', max_length=30, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
