# Generated by Django 4.1.7 on 2024-04-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_smslog_phone_alter_smslog_subject_alter_smslog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
