# Generated by Django 4.1.7 on 2024-06-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_smslog_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('not_seen', 'خوانده نشده'), ('seen', 'خوانده شده')], default='not_seen', max_length=10),
        ),
    ]
