# Generated by Django 4.1.7 on 2024-06-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('not_seen', 'جدید'), ('seen', 'خوانده شده')], default='not_seen', max_length=10, verbose_name='وضعیت'),
        ),
    ]
