# Generated by Django 4.1.7 on 2024-08-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_contactmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مشاهده'),
        ),
    ]
