# Generated by Django 4.1.7 on 2024-08-28 22:10

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contactmessage_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[accounts.validators.phone_number_validator], verbose_name='تلفن همراه'),
        ),
    ]
