# Generated by Django 4.1.7 on 2024-08-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'پیام ارتباط با ما', 'verbose_name_plural': 'پیام های ارتباط با ما'},
        ),
    ]
