# Generated by Django 4.1.7 on 2024-09-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_siteinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
